authors = ["LiterallyWize"]
description = "A relatively fast, pure Luau PNG library"
includes = [
    "pesde.toml",
    "LICENSE",
    "README.md",
    "bin/PNGuin.luau",
]
license = "MIT"
name = "literallywize/pnguin"
repository = "https://github.com/LiterallyWize/PNGuin"
version = "1.0.1"

[indices]
default = "https://github.com/pesde-pkg/index"

[target]
environment = "luau"
lib = "bin/PNGuin.luau"
