authors = ["LiterallyWize"]
description = "A relatively fast PNG library for Luau"
includes = [
    "pesde.toml",
    "LICENSE",
    "README.md",
    "bin/PNGuin.luau",
]
license = "MIT"
name = "literallywize/pnguin"
repository = "https://github.com/LiterallyWize/PNGuin"
version = "1.0.0"

[indices]
default = "https://github.com/pesde-pkg/index"

[target]
lib = "bin/PNGuin.luau"
environment = "luau"
