[package]
name = "literallywize/pnguin"
description = "A relatively fast PNG library written in Luau"
version = "1.0.0"
license = "MIT"
authors = "LiterallyWize"
repository = "https://github.com/LiterallyWize/PNGuin"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["*"]
include = ["src", "LICENSE"]